concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "doc"
  url = "http://gitlab.local/"
  token = "xxxxxxxxxxxx"
  tls-ca-file = "/etc/gitlab-runner/certs/gitlab.local.crt"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    host = "tcp://172.30.160.1:2375"
    tls_verify = false
    image = "ubuntu"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock", "/etc/gitlab-runner/certs:/etc/gitlab-runner/certs"]
    extra_hosts = ["gitlab.local:172.30.160.1"]
    shm_size = 0

[[runners]]
  name = "doc"
  url = "http://gitlab.local/"
  token = "xxxxxxxxxxxx"
  tls-ca-file = "/etc/gitlab-runner/certs/gitlab.local.crt"
  executor = "docker"
  [runners.custom_build_dir]
  [runners.cache]
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    network_mode = "gitlab_net"
    extra_hosts = ["gitlab.local:172.30.160.1"]
    host = "tcp://172.30.160.1:2375"
    tls_verify = false
    image = "ubuntu:20.04"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache", "/var/run/docker.sock:/var/run/docker.sock", "/etc/gitlab-runner/certs:/etc/gitlab-runner/certs"]
    shm_size = 0
