version: "3.8"
services:
  gitlab:
    build:
      context: .
      shm_size: '256m'
    hostname: gitlab.local
    restart: always
    environment:
      DOCKER_HOST: 'tcp://192.168.0.101:2375'
      DOCKER_CERT_PATH: '/etc/gitlab/ssl'
      DOCKER_TLS_VERIFY: 1
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
    ports:
      - "80:80"
      - "22:22"
      - "443:443"
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab_net

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restart: always
    depends_on:
      - gitlab
    environment:
      DOCKER_HOST: 'tcp://192.168.0.101:2375'
      GIT_SSL_NO_VERIFY: true
      DOCKER_TLS_VERIFY: 1
      COMPOSE_CONVERT_WINDOWS_PATHS: 1
    extra_hosts:
      - "gitlab.local:192.168.0.101"
    ports:
      - "2375:2375"
    volumes:
      - gitlab-runner:/etc/gitlab-runner
      - //var/run/docker.sock:/var/run/docker.sock
    networks:
      - gitlab_net

networks:
  gitlab_net:

volumes:
  gitlab-config:
    external: true
  gitlab-logs:
    external: true
  gitlab-data:
    external: true
  gitlab-runner:
    external: true